### ISSUE TITLE
The first request doesn't have a collectionId

### ISSUE THREAD

**Issue by Ullaakut** [pixelfusion/blueman#24]
And thus the collection can't be imported in Postman. Adding the collectionId manually fixes the Issue.

This happens ONLY to the first request of the file. Re-converting the Blueprint doesn't fix the problem.

I can't show the .json / .md files I converted as they contain confidential data.

**Comment by sefsinalas** [comment]
I have the same error

**Comment by Ullaakut** [comment]
I sent an email to @kielabokkie with the piece of code that seems to be responsible for the problem, it should probably be fixed soon :- )

**Comment by kielabokkie** [comment]
@Ullaakut @sefsinalas I've released Blueman [v1.3.1](https://github.com/pixelfusion/blueman/releases/tag/1.3.1) which solves this issue.

If you are using the .phar file just update using the `self-update` function:

    $ blueman self-update
